# Generated by Django 6.0.1 on 2026-01-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INSCRITA', 'Inscrita'), ('RETIRADA', 'Retirada')], max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'unique_together': {('student', 'section')},
            },
        ),
    ]
