# Generated by Django 6.0.1 on 2026-01-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.career')),
                ('prerequisites', models.ManyToManyField(related_name='required_by', through='academics.Prerequisite', to='academics.subject')),
            ],
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_subject', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_subject', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('subject', 'prerequisite')},
        ),
    ]
