# Generated by Django 6.0.1 on 2026-01-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='credits',
            new_name='UC',
        ),
        migrations.AddField(
            model_name='subject',
            name='HL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='HT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='TH',
            field=models.IntegerField(default=0),
        ),
    ]
