# Generated by Django 6.0.1 on 2026-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_credits_subject_uc_subject_hl_subject_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='HL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='HP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='HT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='TH',
            field=models.IntegerField(),
        ),
    ]
